name: dtw_measure
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - h5py
  - matplotlib
  - seaborn
  - pytables
  - torchvision
  - scikit-learn
  - scipy
  - pytorch
